// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTtLGIdL1iD9boysZVRQheueUkTYMBg0',
    appId: '1:155953141218:web:26bf0734c3ca5f54fc15bb',
    messagingSenderId: '155953141218',
    projectId: 'acvmx-app-61557',
    authDomain: 'acvmx-app-61557.firebaseapp.com',
    storageBucket: 'acvmx-app-61557.firebasestorage.app',
    measurementId: 'G-4E9LLJSRQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuroKHnVtXLPBuP_peuknAkkCmhgoynE',
    appId: '1:155953141218:android:90ba375339084ba4fc15bb',
    messagingSenderId: '155953141218',
    projectId: 'acvmx-app-61557',
    storageBucket: 'acvmx-app-61557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9CKpKAuoR3PRnhdicdokZyI6BaeHep4',
    appId: '1:155953141218:ios:fdbfe202751e211efc15bb',
    messagingSenderId: '155953141218',
    projectId: 'acvmx-app-61557',
    storageBucket: 'acvmx-app-61557.firebasestorage.app',
    iosBundleId: 'com.younderbot.acvmx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9CKpKAuoR3PRnhdicdokZyI6BaeHep4',
    appId: '1:155953141218:ios:29a8019b4ffd8786fc15bb',
    messagingSenderId: '155953141218',
    projectId: 'acvmx-app-61557',
    storageBucket: 'acvmx-app-61557.firebasestorage.app',
    iosBundleId: 'younderbots.com.acvmx',
  );

}